### ISSUE TITLE
Have to permission to access this module

### ISSUE THREAD

**Issue by LiuLang** [BenOckmore/mutagen#20]
Hi, I installed mutagen on Debian sid, but found some problems:

`/usr/local/lib/python3.3/dist-packages # ls -l
total 8
drwx--S--- 3 root staff 4096 Oct 14 19:12 mutagenx
-rw------- 1 root staff  832 Oct 14 19:12 mutagenx-1.22.egg-info`

Normal user does not have permission to import this moudle.

`mid3iconv2` and other files in /usr/local/bin/ throw errors. I read the source file and found out that it uses python2-mutagen module. Would you please port those files to python3?

mutagenx modules is used in my project: https://github.com/LiuLang/kwplayer

And thanks for what you've done. :)

**Comment by BenOckmore** [comment]
Hi, thanks for your feedback! Could you tell me what command you used to install the mutagenx package, and the exact error/exception you're getting? I'll try to look into it today.

I'll also look into porting the tools, but that's probably not going to be done until I release the 1.22 version on PyPI. I'll make a separate issue for it...

**Comment by LiuLang** [comment]
`./setup.py build` and `su -c "./setup.py install"`

Content of mutagenx/:

```
/usr/local/lib/python3.3/dist-packages/mutagenx # ls -l
total 336
-rw------- 1 root staff 16850 Sep 30 16:52 apev2.py
-rw------- 1 root staff 22332 Sep 30 16:52 asf.py
-rw------- 1 root staff  3372 Sep 30 16:52 _constants.py
-rw------- 1 root staff 14864 Sep 30 16:52 easyid3.py
-rw------- 1 root staff  8204 Sep 30 16:52 easymp4.py
-rw------- 1 root staff 28078 Sep 30 16:52 flac.py
-rw------- 1 root staff 79021 Sep 30 16:52 id3.py
-rw------- 1 root staff  7178 Sep 30 16:52 __init__.py
-rw------- 1 root staff  2839 Sep 30 16:52 monkeysaudio.py
-rw------- 1 root staff  9498 Sep 30 16:52 mp3.py
-rw------- 1 root staff 27184 Sep 30 16:52 mp4.py
-rw------- 1 root staff  8788 Sep 30 16:52 musepack.py
-rw------- 1 root staff  4340 Sep 30 16:52 oggflac.py
-rw------- 1 root staff  3495 Sep 30 16:52 oggopus.py
-rw------- 1 root staff 17867 Sep 30 16:52 ogg.py
-rw------- 1 root staff  4128 Sep 30 16:52 oggspeex.py
-rw------- 1 root staff  3882 Sep 30 16:52 oggtheora.py
-rw------- 1 root staff  4197 Sep 30 16:52 oggvorbis.py
-rw------- 1 root staff  2182 Sep 30 16:52 optimfrog.py
drwx--S--- 2 root staff  4096 Oct 15 02:43 __pycache__
-rw------- 1 root staff  1896 Sep 30 16:52 trueaudio.py
-rw------- 1 root staff  8519 Sep 30 16:52 _util.py
-rw------- 1 root staff  8012 Sep 30 16:52 _vorbis.py
-rw------- 1 root staff  1794 Sep 30 16:52 wavpack.py
```

but command files in /usr/local/bin are OK.

**Comment by LiuLang** [comment]
Sorry, that problem is caused by my system. I tried to install other python module with easy_install3, the same situation occurs. I'll try to find out how did that happen.

**Comment by JonnyJD** [comment]
just a wild guess, but what does `umask` say in /usr/local/lib ?

**Comment by LiuLang** [comment]
Right.
It's caused by umask, umask value in my root env is 0077. I tested in virtualbox(debian wheezy), its default umask is 0022.

Aha, `umask 0022` is commented in my /root/.bashrc. :)

**Comment by BenOckmore** [comment]
Ok, closing this as invalid if you think it's a problem your end. Thanks for the report - I've created a new issue for the tools part - #21 .
