### ISSUE TITLE
Setup.py fails with running build_py 

### ISSUE THREAD

**Issue by bedekelly** [BenOckmore/mutagen#26]
Running `setup.py install` gives this message at time of posting:
    `error: package directory 'mutagenx' does not exist`

Renaming the `mutagen` folder to `mutagenx` resolves this issue.

(closed, sorry, I'm dumb and don't read install instructions)

**Comment by BenOckmore** [comment]
I've had reports of this before, and I thought I'd already made an issue. I believe that this is an actual problem, and not just an issue with the way you installed. Could you let me know what ended up working for you?

Thanks!

**Comment by apseudonym** [comment]
I had the same issue.
Changing the directory's name didn't do anything, however after going into setup.py and changing `packages=['mutagenx']` to `packages=['mutagen']` it installed properly

**Comment by BenOckmore** [comment]
Oh I thought I fixed this around the time I did the last release - did you get this recently in the latest master branch? Thanks for reporting!

**Comment by apseudonym** [comment]
Yeah, I actually downloaded your release today because pytaglib didn't want
to build for me. Looking at the master branch, it doesn't look changed.

**Comment by Wikunia** [comment]
I have the same problem: Windows 8.1 
Is there any solution?

**Comment by BenOckmore** [comment]
Should be fixed now in the latest commit. Thanks to apseudonym for effectively solving it for me!
