### ISSUE TITLE
mutagenx-1.23.1 is not pip installable (python 3.3)

### ISSUE THREAD

**Issue by enku** [BenOckmore/mutagen#27]
1.23 installs fine, but 1.23.1 gives:

```
SyntaxError: invalid or missing encoding declaration for 'tools/moggsplitc'
Complete output from command /opt/teamplayer/bin/python3.3 -c "import setuptools;__file__='/opt/teamplayer/build/mutagenx/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-v32o38-record/install-record.txt --single-version-externally-managed --install-headers /opt/teamplayer/include/site/python3.3:
```

$  moggsplitc
moggsplitc: python 2.7 byte-compiled

**Comment by enku** [comment]
Actually there are a lot of files that end in "c" in the tools directory.  The file command says they're all "python 2.7 byte-compiled".

https://pypi.python.org/packages/source/m/mutagenx/mutagenx-1.23.1.tar.gz#md5=c5acfeb3a90a3356dd127f2db458dca1

**Comment by BenOckmore** [comment]
Hi, I can't reproduce the problem using `pip install mutagenx` or `pip install mutagenx --upgrade`, but those files shouldn't be in the package anyway, so I've removed and re-uploaded as mutagenx 1.23.2. Please let me know if this fixes the issue for you.

**Comment by BenOckmore** [comment]
Managed to reproduce it when I created a virtualenv using Python 3, and it looks like the new update (1.23.2) does fix the issue.

Thanks for reporting!

**Comment by enku** [comment]
Thanks!
